# Generated by Django 5.0.7 on 2024-11-11 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0004_remove_task_worker_remove_worker_skill_task_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('material', 'Material'), ('equipment', 'Equipment'), ('labor', 'Labor')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application1.project')),
            ],
        ),
    ]
